version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ddbb:/var/lib/mysql
     restart: always
     ports:
      - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress
     volumes:
       - wp:/var/www
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
     ports:
      - "80:80"
volumes:
  ddbb:
  wp:
